### ISSUE TITLE
Some /maps/id/ -endpoints don't exist in tempus2 API

### ISSUE THREAD

**Issue by laurirasanen** [arispoloway/tempus-api-graphql#50]
Some `/maps/id/...` -endpoints don't exist in `tempus2.xyz/api/v0`.

For example:

| broken | works |
| ------- | ------ |
| https://tempus2.xyz/api/v0/maps/id/1/fullOverview2 | https://tempus2.xyz/api/v0/maps/name/jump_beef/fullOverview2 |
| https://tempus2.xyz/api/v0/maps/id/1/zones/typeindex/map/1/records/player/1/3 | https://tempus2.xyz/api/v0/maps/name/jump_beef/zones/typeindex/map/1/records/player/1/3 |

Minimal repro query:
```graphql
{
  player(id: 76057) {
    record(mapName: "jump_beef", class: SOLDIER) {
      map {
        name
      }
    }
  }
}
```

On https://tempus.nolem.me/ it dumps `Cannot read properties of null (reading 'map_info')`. Using the library locally just throws 404 from axios.

**Comment by laurirasanen** [comment]
I'm currently using this as a dirty workaround just to get things running :]

```diff
--- a/lib/tempus.js
+++ b/lib/tempus.js
@@ -20,7 +20,8 @@ function newCachedTempusFetcher(fetchResponseByURL) {
     return r;
   });
   fetcher.mapsById = new CachedByKeyResource(async (id) => {
-    const r = await fetchResponseByURL(`maps/id/${id}/fullOverview2`);
+    const tmp = await fetchResponseByURL(`maps/id/${id}/fullOverview`);
+    const r = await fetchResponseByURL(`maps/name/${tmp.map_info.name}/fullOverview2`);
     fetcher.mapsByName.set(r.map_info.name, r);
     return r;
   });
```

**Comment by arispoloway** [comment]
Thanks for finding - I asked about it in the discord to see if it could be added since that's the ideal resolution here, but if that takes a while I'll work around it.

**Comment by arispoloway** [comment]
Endpoints were added so this isn't an issue any more
